### ISSUE TITLE
Error on Cushy diffusion load

### ISSUE THREAD

**Issue by Withoutblwd** [rvion/CushyStudio#228]
Encountered the following errors:

![image_2024-06-07_223503917](https://github.com/rvion/CushyStudio/assets/64270381/cfe83fdd-f6a9-4bd5-bce5-dcdb123fce8d)

And when attempting to press test on host in hosts menu:
![image](https://github.com/rvion/CushyStudio/assets/64270381/1739a2a8-0ac8-4e5f-957f-a8e564319afe)

OS: Windows 10 64bit

**Comment by rvion** [comment]
thanks for the report !
first bug is fixed upstream in some dev branch; will try to merge asap

Second problem is related to not beeing able to connect to some ComfyUI backend to retrieve the list of nodes
Maybe you have to configure you host to properly point to your ComfyUI setup ?

maybe your comfyUI, if on some cloud machine, require https + port 443 ?
maybe your comfyUI, if on some local network machine, require to be started with --listen 0.0.0.0 or something similar to accept incominc connections ?

**Comment by Withoutblwd** [comment]
Thank you for your response. 
I apologize for not mentioning this earlier, but I am running ComfyUI on the same machine. 
I tried adding both --listen 0.0.0.0 and --listen 127.0.0.1, but the error persisted. Here is my host setup:
![image](https://github.com/rvion/CushyStudio/assets/64270381/e1d28967-e64e-4997-a77d-4b98bb9a9187)

I will check all the branches to see if my first error is fixed on any of those.
